// components/Nav.jsx
import Link from "next/link";

export default function Nav() {
  return (
    <nav>
      <div className="flex justify-between">
        <div className="grid content-center p-4 text-base font-bold">
          <Link href="/">Home</Link>
        </div>
        <div className="grid content-center p-4 text-right">
          <h1 className="text-2xl font-bold">Ian Pratt</h1>
          <h3 className="">Just a gay programmer</h3>
        </div>
      </div>
      <hr />
    </nav>
  );
}

// src/lib/Nav.svelte
<nav>
  <div class="wrap">
    <div class="links">
      <a href="/">Home</a>
    </div>
    <div>
      <h1>Ian Pratt</h1>
      <h3>Just a gay programmer</h3>
    </div>
  </div>
</nav>
<hr />

<style>
  .wrap {
    display: flex;
    box-sizing: border-box;
    justify-content: space-between;
    align-items: center;
  }

  .links > * {
    font-size: 120%;
  }
</style>
