// src/lib/components/Nav.svelte
<script lang="ts">
  import DropdownMenu from "$lib/components/DropdownMenu.svelte";
</script>

<nav class="space-y-0">
  <div class="px-4 py-1 flex box-border justify-between items-center">
    <DropdownMenu>
      <a href="/">Index</a>
      <a href="/blog">Blog</a>
      <a href="https://github.com/cogsandsquigs">Github</a>
    </DropdownMenu>
    <div class="text-right text-xs sm:text-sm md:text-lg space-y-0">
      <h2 class="m-0">Ian Pratt</h2>
      <h3>Just a gay programmer</h3>
    </div>
  </div>
  <hr />
</nav>

// components/Nav.jsx
import Link from "next/link";

export default function Nav() {
  return (
    <nav>
      <div className="flex justify-between">
        <div className="grid content-center p-4 text-base font-bold">
          <Link href="/">Home</Link>
        </div>
        <div className="grid content-center p-4 text-right">
          <h1 className="text-2xl font-bold">Ian Pratt</h1>
          <h3 className="">Just a gay programmer</h3>
        </div>
      </div>
      <hr />
    </nav>
  );
}
